@startuml FrontendUses
skinparam actorStyle Hollow
left to right direction
:User: as u
:Backend: as b

package App {
    usecase "create task" as c_task
    usecase "delete existing task" as d_task
    usecase "update existing task" as u_task
    usecase "view tasks" as v_task
    usecase "create financical category" as c_finance
    usecase "delete existing financial category" as d_finance
    usecase "manage finance category" as m_finance
    usecase "view financial categories" as v_finance
    usecase "create habit" as c_habit
    usecase "delete existing habit" as d_habit
    usecase "manage existing habit" as u_habit
    usecase "view habits" as v_habit
    usecase "update settings configuration" as u_settings
    usecase "view settings configuration" as v_settings
}

u --> c_task
c_task --> b
u --> d_task
d_task --> b
u --> u_task
u_task --> b
u --> v_task
v_task <-> b

u --> c_finance
c_finance --> b
u --> d_finance
d_finance --> b
u --> m_finance
m_finance --> b
u --> v_finance
v_finance <-> b

u --> c_habit
c_habit --> b
u --> d_habit
d_habit --> b
u --> u_habit
u_habit --> b
u --> v_habit
v_habit <-> b

u --> v_settings
v_settings <-> b
u --> u_settings
u_settings --> b

@enduml

@startuml BackendUses

@enduml